import java.awt.event.WindowAdapter;
import java.util.Vector;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class UserGUI extends javax.swing.JFrame {
	
	// Variables declaration - do not modify                     
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton discardBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.table.DefaultTableModel tblModel;
    private static final long serialVersionUID = 1L;
    // End of variables declaration
    /**
     * Creates new form UserGUI
     */
    public UserGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        discardBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);      
        setTitle("Book Management Application");

        addBtn.setText("New");

        searchBtn.setText("Search");

        saveBtn.setText("Save Change");
        saveBtn.setEnabled(false);

        discardBtn.setText("Discard");
        discardBtn.setEnabled(false);

        removeBtn.setText("Remove");
        removeBtn.setEnabled(false);

        editBtn.setText("Edit");
        editBtn.setEnabled(false);
        
        bookTable.setDefaultEditor(Object.class, null);
        bookTable.setFillsViewportHeight(true);
        
        jScrollPane2.setViewportView(bookTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backBtn.setText("Back To Book List");
        backBtn.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(discardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(625, 625, 625)
                .addComponent(backBtn)
                .addContainerGap(586, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(discardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGap(19, 19, 19)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }
    
    public void addBtnActionPerformed(java.awt.event.ActionListener evt) {                                         
    	addBtn.addActionListener(evt);
    }
    
    public void backBtnActionPerformed(java.awt.event.ActionListener evt) {                                         
    	backBtn.addActionListener(evt);
    }
    
    public void discardBtnActionPerformed(java.awt.event.ActionListener evt) {                                         
    	discardBtn.addActionListener(evt);
    }
    
    public void editBtnActionPerformed(java.awt.event.ActionListener evt) {                                         
    	editBtn.addActionListener(evt);
    }
    
    public void removeBtnActionPerformed(java.awt.event.ActionListener evt) {                                         
    	removeBtn.addActionListener(evt);
    }
    
    public void saveBtnActionPerformed(java.awt.event.ActionListener evt) {                                         
    	saveBtn.addActionListener(evt);
    }
    
    public void searchBtnActionPerformed(java.awt.event.ActionListener evt) {                                         
    	searchBtn.addActionListener(evt);
    }
    
    public void tableListener(ListSelectionListener lsl){
    	bookTable.getSelectionModel().addListSelectionListener(lsl);
    }
    
    public javax.swing.JTable getBookTable() {
		return bookTable;
	}
    
    public void windowListener(WindowAdapter wa) {
    	addWindowListener(wa);
    }
    

	public void setTable(Vector<Vector<Object>> data) {
    	Vector<String> header = new Vector<String>();
    	header.add("ISBN");
    	header.add("Title");
    	header.add("Author");
    	header.add("Publisher");
    	header.add("Genres");
    	header.add("Price");
    	header.add("Quantity");
    	tblModel = (DefaultTableModel)bookTable.getModel();
    	tblModel.setDataVector(data, header);
    }
    
    public void setSaveBtnEnabled(){
    	saveBtn.setEnabled(true);
    }
    
    public void setEditBtnEnabled(){
    	editBtn.setEnabled(true);
    }
    
    public void setRemoveBtnEnabled(){
    	removeBtn.setEnabled(true);
    }
    
    public void setDiscardBtnEnabled(){
    	discardBtn.setEnabled(true);
    }
    
    public void setBackBtnEnabled(){
    	backBtn.setEnabled(true);
    }
    
    public void setSaveBtnDisabled(){
    	saveBtn.setEnabled(false);
    }
    
    public void setEditBtnDisabled(){
    	editBtn.setEnabled(false);
    }
    
    public void setRemoveBtnDisabled(){
    	removeBtn.setEnabled(false);
    }
    
    public void setDiscardBtnDisabled(){
    	discardBtn.setEnabled(false);
    }
    
    public void setBackBtnDisable(){
    	backBtn.setEnabled(false);
    }

}
